language: node_js

node_js: stable

cache:
  directories:
    - npm
    - node_modules

before_install:
  - npm i -g npm@6.4.1

install:
  - npm install

script:
  - npm run build

after_success:
  - cd ./dist
  - git init
  - git config user.name "Clooooode"
  - git config user.email "jackey8616@gmail.com"
  - git add .
  - git commit -m "Travis Build Bot Update"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/jackey8616/Silverfish-vue" master:gh-pages

branches:
  only:
    - master